import logging
import time
from pathlib import Path

from fpdf import FPDF

from ..config import config
from ..database import DatabaseManager

logger = logging.getLogger(__name__)


class AgencyReport(FPDF):
    """PDF report generator for client performance summaries."""

    def __init__(self, client_name: str) -> None:
        super().__init__()
        self.client_name: str = client_name
        self.logo_path: str | None = None

    def header(self) -> None:
        """Add header to each page."""
        # Agency Logo (If you have one, set it here)
        # self.image('agency_logo.png', 10, 8, 33)
        self.set_font("Arial", "B", 15)
        _ = self.cell(80)  # Move to right
        _ = self.cell(30, 10, "Monthly Performance Report", 0, 0, "C")
        self.ln(20)

        # Sub-header
        self.set_font("Arial", "I", 10)
        _ = self.cell(
            0, 10, f"Client: {self.client_name} | Generated by AgencyOS", 0, 1, "R"
        )
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self) -> None:
        """Add footer to each page."""
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        _ = self.cell(0, 10, f"Page {self.page_no()}", 0, 0, "C")


class ReportGenerator:
    """Generates client performance reports as PDFs."""

    def __init__(self, db: DatabaseManager | None = None) -> None:
        self.db: DatabaseManager = db if db else DatabaseManager()
        self.output_dir: Path = config.GENERATED_DIR

    def generate_client_report(self, client_name: str) -> str:
        """
        Creates a PDF summary of performance.
        """
        logger.info(f"📄 Generating report for {client_name}...")

        # 1. Fetch Data
        df = self.db.get_analytics()

        # In a real SaaS, you'd filter by client_name here
        # df = df[df['client'] == client_name]

        total_views = df["views"].sum() if not df.empty else 0
        total_likes = df["likes"].sum() if not df.empty else 0
        total_posts = len(df)

        # 2. Build PDF
        pdf = AgencyReport(client_name)
        pdf.add_page()

        # Section: Executive Summary
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "1. Executive Summary", 0, 1)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(
            0,
            10,
            f"This month, we published {total_posts} pieces of content for {client_name}. "
            f"The campaign generated a total of {total_views:,} views and {total_likes:,} engagements.",
        )
        pdf.ln(5)

        # Section: Key Metrics
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "2. Key Metrics", 0, 1)

        # Draw a simple table
        pdf.set_font("Arial", "B", 12)
        pdf.cell(60, 10, "Metric", 1)
        pdf.cell(60, 10, "Value", 1)
        pdf.ln()

        pdf.set_font("Arial", "", 12)
        pdf.cell(60, 10, "Total Posts", 1)
        pdf.cell(60, 10, str(total_posts), 1)
        pdf.ln()
        pdf.cell(60, 10, "Total Views", 1)
        pdf.cell(60, 10, f"{total_views:,}", 1)
        pdf.ln()
        pdf.cell(60, 10, "Engagement (Likes)", 1)
        pdf.cell(60, 10, f"{total_likes:,}", 1)
        pdf.ln(10)

        # Section: AI Insights (Mocked for now, can use Brain later)
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "3. Strategy Insights", 0, 1)
        pdf.set_font("Arial", "", 11)
        pdf.multi_cell(
            0,
            10,
            "- Video content is performing 20% better than static images.\n"
            "- The 'Cyberpunk' aesthetic resonated well with the target audience.\n"
            "- Recommendation: Double down on short-form video for next week.",
        )

        # Save
        filename = f"Report_{client_name.replace(' ', '_')}_{int(time.time())}.pdf"
        output_path = self.output_dir / filename
        pdf.output(str(output_path))

        return str(output_path)
